### ISSUE TITLE
Getting exception qappimageupdate.hpp: No such file or directory

### ISSUE THREAD

**Issue by probal31** [antony-jr/AppImageUpdaterBridge#31] opened 2021-10-20 06:30 UTC
Hello,

I was trying to integrate the `QAppImageUpdate` library as git submodules to one of the exting cmake project.

Followed the instructions as mentioned in the link: https://antonyjr.in/QAppImageUpdate/docs/Installation.html

Some it gives exception regarding header not found.
I will try to provide all the details that was done.

Here is the project structure:
```
- MyApp
  -- lib
    -- QAppImageUpdate
    -- CMakeLists.txt
  -- src
    ...
    -- CMakeLists.txt
    ...
  CMakeLists.txt
```

Added the library to existing project as submodules:
```
$ git submodule init
$ git submodule add https://github.com/antony-jr/QAppImageUpdate lib/QAppImageUpdate
$ git submodule update
```

In the top level `CMakeLists.txt`, have added the below snippet:
```
add_subdirectory(lib)
```

Added new `lib -> CMakeLists.txt` file:
```
# Add include directory
include_directories(QAppImageUpdate)

# include subdirectories 
add_subdirectory(QAppImageUpdate)
```

In the `src -> CMakeLists.txt`, have added the below snippet:
```
target_link_libraries(${PROJECT_NAME} ... ... QAppImageUpdate)
```

Next in one of the cpp file tried to include the QAppImageUpdate:
```
#include <QAppImageUpdate>
```

The `cmake` runs with no error but the `make` command gives the below exception.

```
In file included from /home/probal/code-workspace/nx-software-center-workspace/nx-software-center/src/models/appsmodel.cpp:13:
/home/probal/code-workspace/nx-software-center-workspace/nx-software-center/lib/QAppImageUpdate/QAppImageUpdate:35:10: fatal error: qappimageupdate.hpp: No such file or directory
   35 | #include "qappimageupdate.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Can you please mention what is wrong here? \
If there is anything that have been missed or not mentioned in the installation document?

Thanks.

**Comment by antony-jr** [comment] 2021-10-20 09:08
@probal31 Thanks for reporting. I will test this in my local machine and ping you back. (**Although installing it to the system and using it would be very easy with find_package**).

This is probably a mistake in the CMakeLists.txt

**Comment by antony-jr** [comment] 2021-10-20 09:50
@probal31 The issue is **fixed now**. Please try the latest master. Also lib/CMakeLists.txt does not require include_directory anymore, 

lib/CMakeLists.txt file:
```
add_subdirectory(QAppImageUpdate)
```


The above is sufficient.

The next version documentation is [here](https://antonyjr.in/QAppImageUpdate/versions.html) (i.e The latest one from master branch).

**Comment by probal31** [comment] 2021-10-20 10:18
@antony-jr Thanks.. 👍 

Yes now I have installed it in the system and using it with find_package.

Also checked the latest master and the issue seems to be not coming now.

**Comment by antony-jr** [comment] 2021-10-20 10:20
Closing the issue as it is resolved now. Thank you for your time. :+1:

**Closed as completed by antony-jr** 2021-10-20 10:20 UTC
